version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3030:3000"
    volumes:
      - /app/node_modules
      - .:/app
    tty: true

  appfortesing:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    tty: true
    command: ["npm", "run", "test"]